export const authActionTypes = {
  GET_LOGIN_REQUEST: 'GET_LOGIN_REQUEST',
  GET_LOGIN_SUCCESS: 'GET_LOGIN_SUCCESS',
  GET_LOGIN_FAIL: 'GET_LOGIN_FAIL',

  GET_REGISTER_REQUEST: 'GET_REGISTER_REQUEST',
  GET_REGISTER_SUCCESS: 'GET_REGISTER_SUCCESS',
  GET_REGISTER_FAIL: 'GET_REGISTER_FAIL',
};
