export const venuesActionTypes = {
  GET_VENUE_LIST_REQUEST: 'GET_VENUE_LIST_REQUEST',
  GET_VENUE_LIST_SUCCESS: 'GET_VENUE_LIST_SUCCESS',
  GET_VENUE_LIST_FAIL: 'GET_VENUE_LIST_FAIL',

  GET_VENUE_DETAIL_REQUEST: 'GET_VENUE_DETAIL_REQUEST',
  GET_VENUE_DETAIL_SUCCESS: 'GET_VENUE_DETAIL_SUCCESS',
  GET_VENUE_DETAIL_FAIL: 'GET_VENUE_DETAIL_FAIL',
};
